#ifndef MANAMATCHER_H_LIBMAGIC_2015_17_05
#define MANAMATCHER_H_LIBMAGIC_2015_17_05

#include "../board/ManaPool.h"
#include "../cards/Cost.h"
#include "MatcherSolutions.h"

namespace mtg {

class ManaMatcher {
	matcher::Solutions solutions;
	size_t maxSolutions;
public:
	ManaMatcher(size_t maxSolutions = 1);
	// annotations argument is generated by someFunction(gameStep, sourceOfCost)
	ManaMatcher & match(Cost const & cost, ManaPool const & manaPool, Mana::Annotations annotations = 0);
	explicit operator bool() const { return ! solutions.empty(); }
	matcher::Solutions const & getSolutions() const { return solutions; }
};

} /* namespace mtg */

#endif /* MANAMATCHER_H_ */
